#! /usr/bin/bash

#gets battery info
batteryInfo="$(acpi)"


printHelp () {
    echo "
Usage: battery [COMMAND]

Commands:
    amount - returns the battery charge from "0" to "100"
    charging - returns true if the battery is charging. 
    details - returns the full details of the battery.
    time - prints time remaining to charge or till depleted.
"
}

 notCharging () {
    chargingColumn="$(awk '{ print $3 }' <<< "$batteryInfo" )"
    if test "$chargingColumn" == "Charging,"; then
        return 1
    elif test "$chargingColumn" == "Full,"; then
        return 1
    else
        return 0
    fi
}

checkMessageOpen () {
    makoctl list | jq ".data[0] | map(select(.[\"app-name\"].data == \"$1\")) | length > 0"
}

writeWarning () {
    if test "$(checkMessageOpen "$2")" == "false";then
        notify-send -e -t 0 -a "$2" System "$1"
        #notify-send -i /usr/share/Adwaita/symbolic/status/battery-low-symbolic.svg -e -t 0 -a "$2" System "$1"
    fi
}

printAmount () {
    local amount=$(awk '{ print $4 }' <<< "$batteryInfo" | tr -d "[%,]")
    if (( amount <= 5 )) && notCharging; then
        writeWarning "Battery Below 5%!" "batteryWarning" && export WARNED_BATTERY=true
    fi
    echo "$amount"
}

printCharging () {
    chargingColumn="$(awk '{ print $3 }' <<< "$batteryInfo" )"
    if test "$chargingColumn" == "Charging,"; then
        echo "true"
    elif test "$chargingColumn" == "Full,"; then
        echo "true"
    else
        echo "false"
    fi
}

printDetails () {
    echo "$batteryInfo"
}

printTime () {
    time=$(awk '{ print $5 }' <<< "$batteryInfo")
    echo $time
}

if test "$1" == ""; then
    printHelp
elif test "$1" == "help"; then
    printHelp
elif test "$1" == "amount"; then
    printAmount
elif test "$1" == "charging"; then
    printCharging
elif test "$1" == "details"; then
    printDetails
elif test "$1" == "time"; then
    printTime
else
    printHelp
fi
