#! /usr/bin/bash

# this will get the total network download and upload in mbps. output: json
#

networkStateLocation="$HOME/.config/eww/scripts/states/network"
networkTrackingLocation="$HOME/.config/eww/scripts/states/networkHistory"
#cache total download an upload. compare to last total upload/download. return difference = total over time.

printHelp () {
    echo "
Usage: network [COMMAND]

commands:
    help - prints help menu
    tracking - prints json array of past 20 network queries
    interfaces - prints a iteratable list of interfaces
    save - makes application force to save to history (saving is done automatically)
    "
}

formatInterfaceJSON () {
    local interface="$1"
    local download="$2"
    local upload="$3"
    echo "\"${interface}\":{\"download\":${download},\"upload\":${upload}}"
}

getInterfacesJSON () {
    echo "$(ifstat -j | jq '.[] | keys')"
}

getInterfacesTotal () {
    echo "$(ifstat -j | jq -c '.[] | to_entries | map(.value = {download: .value.rx_bytes, upload: .value.tx_bytes} | .) | [({key: "all", value:  {download: (map(.value.download) | add), upload: (map(.value.upload) | add)}}),.[]] | from_entries')"
}

printTotal () {
    local input="[$(getInterfacesTotal),$(cat "$networkStateLocation")]"
    local output=$(jq -c "map(.all) | {download: (.[0].download - .[1].download), upload: (.[0].upload - .[1].upload)}" <<< "$input")
    echo $output
}


printAll () {
    local input="[$(getInterfacesTotal),$(cat "$networkStateLocation")]"
    local output=$(jq -c "map(to_entries) | flatten | group_by(.key) | map(.[0].value.download -= .[1].value.download | .[0].value.upload -= .[1].value.upload) | [.[].[0]] | from_entries" <<< "$input")
    echo $output
}

trackingDistance=20

getHeadTrackingJSONLines () {
    head -n "$trackingDistance" "$networkTrackingLocation"
}

saveTrackingJSON () {
    local flag=true
    echo -e "$1" | jq -c ".[]" | while read line; do
        if $flag; then
            echo "$line" > "$networkTrackingLocation"
        else
            echo "$line" >> "$networkTrackingLocation"
        fi
        flag=false
    done
}


getUpdatedTrackingJSON () {
    local olderStuff=$(getHeadTrackingJSONLines)
    local output=$(printAll)
    while read line; do
        if test "$line" != ""; then
            output="${output},$line"
        fi
    done <<< "$(echo -e "$olderStuff")"
    local output="[${output}]"
    echo "$output"
}

saveTracking() {
    saveTrackingJSON "$(getUpdatedTrackingJSON)"
}
saveSimple () {
    echo "$(getInterfacesTotal)" > $networkStateLocation
}

getBiggestJSON () {
    local history=$1
    local maxs=$(jq -c "map(to_entries) | flatten | group_by(.key) | map({key: .[0].key, value: map(.value[]) | max}) | from_entries" <<< "$history")
    echo "$maxs"
}

if test "$1" == "all"; then
    printAll
    saveSimple
elif test "$1" == "tracking"; then
    everything=$(getUpdatedTrackingJSON)
    saveTracking
    maxs=$(getBiggestJSON "$everything")
    echo "{\"max\":${maxs},\"history\":${everything}}"
elif test "$1" == "save"; then
    saveTracking
    saveSimple
elif test "$1" == "interfaces"; then
    getInterfacesJSON
elif test "$1" == "total"; then
    printTotal
    saveSimple
elif test "$1" == "help"; then
    printHelp
elif test "$1" == ""; then
    printHelp
else
    printHelp
fi
