#! /usr/bin/bash

commandIn="$1"
inputIn="$2"

ignoredWindows=( "bartop|musicBars" )

#functions

closeWindow () {
    eww close $(eww windows | grep "*" | grep -Ev "($ignoredWindows)" | tr -d "*" | tr "\n" " ")
}

openWindow () {
    closeWindow
    eww open "$1" > /dev/null
    eww open windowCloser > /dev/null
}

printHelp () {
    echo "
Usage: windowManger [COMMAND] <INPUT>

Commands:
    help - prints a simple help menu into stdout.
    open <INPUT> - sets INPUT as the active window.
    close - closes and clears the current window."
}



#check mode
if test "$commandIn" == "help"; then
    printHelp
elif test "$commandIn" == ""; then
    printHelp
elif test "$commandIn" == "close"; then
    closeWindow
elif test "$commandIn" == "open"; then
    openWindow "$inputIn"
else
    echo "invalid command"
fi


            

